package pojo;
// Generated 26 Nov, 2015 10:41:00 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User  implements java.io.Serializable  {


     @Id
     private Integer userId;
     private String userName;
     private String email;
     private String password;
     private byte type;
     private Integer shopId;
     private String title;
     private String imageUrl;
     private String imagePath;
     private Date lastLoginDate;
     private byte status;
     private byte language;
     private int addedBy;
     private byte firstBooking;
     private Date createDate;
     private Date updateDate;

    public User() {
    }

	
    public User(String userName, byte type, String title, byte status, byte language, int addedBy, byte firstBooking, Date createDate, Date updateDate) {
        this.userName = userName;
        this.type = type;
        this.title = title;
        this.status = status;
        this.language = language;
        this.addedBy = addedBy;
        this.firstBooking = firstBooking;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }
    public User(String userName, String email, String password, byte type, Integer shopId, String title, String imageUrl, String imagePath, Date lastLoginDate, byte status, byte language, int addedBy, byte firstBooking, Date createDate, Date updateDate) {
       this.userName = userName;
       this.email = email;
       this.password = password;
       this.type = type;
       this.shopId = shopId;
       this.title = title;
       this.imageUrl = imageUrl;
       this.imagePath = imagePath;
       this.lastLoginDate = lastLoginDate;
       this.status = status;
       this.language = language;
       this.addedBy = addedBy;
       this.firstBooking = firstBooking;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public Integer getShopId() {
        return this.shopId;
    }
    
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public byte getLanguage() {
        return this.language;
    }
    
    public void setLanguage(byte language) {
        this.language = language;
    }
    public int getAddedBy() {
        return this.addedBy;
    }
    
    public void setAddedBy(int addedBy) {
        this.addedBy = addedBy;
    }
    public byte getFirstBooking() {
        return this.firstBooking;
    }
    
    public void setFirstBooking(byte firstBooking) {
        this.firstBooking = firstBooking;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


